### ISSUE TITLE
No way to contribute

### ISSUE THREAD

**Issue by Mode-77** [SteelAtlas/Tetris#1]
@SteelAtlas 
Hello,
I'm sorry I made this an issue, but I couldn't find any way to reach out. I was wondering if you were open to contributions for this project?

**Comment by SteelAtlas** [comment]
Thank you for reaching out , i would love to have contributions on this project , 
i have made some changes to my code which i have not pushed yet , i will update this repository in 12 hours ,
meanwhile you could just open a pull request with your changes any time you want

**Comment by SteelAtlas** [comment]
5uperkritical#0

This is my discord  feel free to message me there.

**Comment by Mode-77** [comment]
OK, thanks. I tried that username, but it looks like it didn't work.

**Comment by SteelAtlas** [comment]
Here you can join this server I just made 

https://discord.gg/vUWF5axt

**Comment by Mode-77** [comment]
@SteelAtlas I think we can close this.
